name: Token after merge
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            repository: Sreekanth-Reddy-GB/RepoB
            event-type: sample_push
          
          
#     name: Dispatch to Design system
#     runs-on: ubuntu-latest
#     steps:
#       - name: Emit repository_dispatch
#         uses: mvasigh/dispatch-action@main
#         with:
#           # You should create a personal access token and store it in your repository
#           token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#           repo: Sreekanth-Reddy-GB/RepoB
#           owner: Sreekanth-Reddy-GB
#           event_type: sample_push
